public enum EnemyAttackType
{
    UNKNOWN,
    // Dragon stalet
    DRAGONSTALET,
    DRAGONSTALET_PIXIEPOISION,
    // bloodyshingler
    BLOODYSHINGLER_NORMAL,
    BLOODYSHINGLER_DASH,
    BLOODYSHINGLER_FIREPILLAR,
    // Apes Wolf
    APES_NORMAL,
    APES_SHAKE,
    APES_ROCK,
    APES_DASH,
    APES_ATTACK,
    // North monkey
    NORTHMONKEY_NORMAL,
    NORTHMONKEY_ACID_MISSLE,
    NORTHMONKEY_POISON_COVER,
    NORTHMONKEY_POISON_ATTACK,
    NORTHMONKEY_FIRE_ATTACK,
    NORTHMONKEY_FIRE_COVER
}
